#ifndef IFUSB_H
#define IFUSB_H

#define IFUSB_PACKET_SIZE 64
#define IFUSB_VENDORID 0xF055
#define IFUSB_PRODUCTID 0xCAFE

#define IFUSB_PING 0x10

#define IFUSB_GPIO_SEND 0x80
#define IFUSB_GPIO_RECV 0x81
#define IFUSB_GPIO_CONFIG 0x8F

#define IFUSB_UART_SEND 0xA0
#define IFUSB_UART_RECV 0xA1
#define IFUSB_UART_SET_BAUD_RATE 0xAF

#define IFUSB_SPI_SEND 0xB0
#define IFUSB_SPI_RECV 0xB1
#define IFUSB_SPI_XFER 0xB2
#define IFUSB_SPI_SET_FREQ 0xBF

// same as SPI_CR1_BR_FPCLK_DIV_*
#define IFUSB_SPI_FREQ_24MHZ 0x0
#define IFUSB_SPI_FREQ_12MHZ 0x1
#define IFUSB_SPI_FREQ_6MHZ 0x2
#define IFUSB_SPI_FREQ_3MHZ 0x3
#define IFUSB_SPI_FREQ_1_5MHZ 0x4
#define IFUSB_SPI_FREQ_750KHZ 0x5
#define IFUSB_SPI_FREQ_325KHZ 0x6
#define IFUSB_SPI_FREQ_187KHZ 0x7

#define IFUSB_I2C_SEND 0xC0
#define IFUSB_I2C_RECV 0xC1
#define IFUSB_I2C_XFER 0xC2

#define IFUSB_INPUT_MODE 0
#define IFUSB_OUTPUT_MODE 1

#define IFUSB_OUTPUT_CLR 0
#define IFUSB_OUTPUT_SET 1

enum IFUSB_GPIOS {
	IFUSB_IO0 = 0,
	IFUSB_IO1,
	IFUSB_IO2,
	IFUSB_IO3,
	IFUSB_IO4,
	IFUSB_IO5
};

#endif